# Please make sure to define the following variables via Export or Compose CLI:
# DOCKER_ROOT_FOLDER
# DATAINT_ROOT_FOLDER
version: "3.8"
services:
    Iat_App:
        image: iat/server:test
        restart: "no"
        ports: 
            - "8080:80"
            - "5000:5000"
            - "5001:5001"

    Iat_MongoDB:
        image: iat/mongo:test
        restart: "no"
